language: node_js
dist: trusty
node_js: lts/*
cache:
  directories:
    - "node_modules"
before_script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: true
  on:
    branch: master
